# path: build.yaml
targets:
  $default:
    builders:
      freezed:
        enabled: true
        options:
          # Use freezed's built-in JSON serialization
          json_serializable: true
        generate_for:
          - lib/src/models/*.dart

      drift_dev:
        enabled: true
        options:
          store_date_time_values_as_text: false

